from pathlib import Path
p=Path('index.html')
s=p.read_text()
if 'goalSelector' in s: raise SystemExit(0)
css='''\n.goalPanel{margin:18px 0 22px;padding:20px;border:1px solid #dfe5ee;border-radius:20px;background:#f8fafc}.goalPanel h3{margin:0 0 6px}.goalPanel p{margin:0 0 14px;color:#667085}.goalSelector{display:flex;flex-wrap:wrap;gap:9px}.goalBtn{border:1px solid #cad4e2;background:#fff;color:#071e45;border-radius:999px;padding:10px 14px;font-weight:800;cursor:pointer}.goalBtn.active{background:#071e45;color:#fff;border-color:#071e45}.alignmentBox{background:#fff7d6;border:1px solid #ffcd19;border-radius:20px;padding:20px;margin:18px 0}.alignmentScore{font-size:2.1rem;font-weight:900;color:#071e45}.alignmentGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:14px}.alignmentGrid article{background:#fff;border-radius:14px;padding:14px}.alignmentGrid h4{margin:0 0 7px}.alignmentGrid p{margin:0;color:#475467;font-size:.88rem}@media(max-width:700px){.alignmentGrid{grid-template-columns:1fr}}\n'''
s=s.replace('</style>',css+'</style>',1)
needle='<div class="initiativeGrid">'
goals='''<div class="goalPanel"><h3>1. O que queremos fortalecer em 2027?</h3><p>Escolha o objetivo principal. A mesma combinação pode ser excelente para um objetivo e insuficiente para outro.</p><div class="goalSelector"><button class="goalBtn active" data-goal="Desenvolvimento">Desenvolver pessoas</button><button class="goalBtn" data-goal="Turnover">Reduzir turnover</button><button class="goalBtn" data-goal="Cultura">Fortalecer cultura</button><button class="goalBtn" data-goal="Lideranca">Preparar lideranças</button><button class="goalBtn" data-goal="Experiencia">Melhorar experiência</button><button class="goalBtn" data-goal="Eficiencia">Automatizar o RH</button><button class="goalBtn" data-goal="Dados">Decidir com dados</button><button class="goalBtn" data-goal="Carreira">Estruturar carreira</button></div></div><h3 style="margin:0 0 12px">2. Quais iniciativas entram no cenário?</h3>'''
s=s.replace(needle,goals+needle,1)
needle2='<div class="strategyResult" aria-live="polite"><h3>Impacto da estratégia</h3>'
rep='<div class="strategyResult" aria-live="polite"><div class="alignmentBox"><div class="kicker">ADERÊNCIA AO OBJETIVO</div><div class="alignmentScore" id="alignmentScore">—</div><h3 id="alignmentTitle"></h3><p id="alignmentDiagnosis"></p><div class="alignmentGrid"><article><h4>✓ Forças</h4><p id="alignmentStrength"></p></article><article><h4>△ Lacunas</h4><p id="alignmentGap"></p></article><article><h4>→ Recomendação MAX</h4><p id="alignmentRecommendation"></p></article></div></div><h3>Impacto da estratégia</h3>'
s=s.replace(needle2,rep,1)
# inject logic before existing simulator click listener
mark="document.querySelector('.generateRoadmap')?.addEventListener('click',()=>{"
logic=r'''const goalBtns=[...document.querySelectorAll('.goalBtn')];
goalBtns.forEach(b=>b.addEventListener('click',()=>{goalBtns.forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
const goalConfig={
Desenvolvimento:{label:'Desenvolver pessoas',ideal:['UNIMAX + PDI','Desempenho','LNT & T&D'],support:['People Analytics','Pesquisas'],why:'criar um ciclo de diagnóstico, desenvolvimento, aplicação e acompanhamento'},
Turnover:{label:'Reduzir turnover',ideal:['Pesquisas','Onboarding','Desempenho'],support:['UNIMAX + PDI','People Analytics','GPTW'],why:'atuar sobre experiência, causas de saída, integração e perspectiva de desenvolvimento'},
Cultura:{label:'Fortalecer cultura',ideal:['GPTW','Pesquisas','Onboarding'],support:['UNIMAX + PDI','Max em Movimento'],why:'combinar escuta, experiência, rituais e desenvolvimento alinhado à cultura'},
Lideranca:{label:'Preparar lideranças',ideal:['Desempenho','UNIMAX + PDI','LNT & T&D'],support:['Sólides','People Analytics'],why:'diagnosticar competências e transformar gaps de liderança em desenvolvimento acompanhado'},
Experiencia:{label:'Melhorar experiência',ideal:['Onboarding','Pesquisas','GPTW'],support:['MAX PEOPLE','Max em Movimento'],why:'escutar a jornada e melhorar momentos que influenciam pertencimento e experiência'},
Eficiencia:{label:'Automatizar o RH',ideal:['Automação','MAX PEOPLE','People Analytics'],support:['Sólides'],why:'centralizar fluxos, reduzir tarefas manuais e transformar dados em gestão'},
Dados:{label:'Decidir com dados',ideal:['People Analytics','MAX PEOPLE','Pesquisas'],support:['Desempenho','Automação'],why:'combinar fontes, indicadores, escuta e rotina de análise para apoiar decisões'},
Carreira:{label:'Estruturar carreira',ideal:['UNIMAX + PDI','Desempenho','LNT & T&D'],support:['Sólides','People Analytics'],why:'conectar competências, avaliação, PDI, aprendizagem e próximos passos de carreira'}};
function renderAlignment(selected){const key=goalBtns.find(b=>b.classList.contains('active'))?.dataset.goal||'Desenvolvimento',g=goalConfig[key],idealHits=g.ideal.filter(x=>selected.includes(x)),supportHits=g.support.filter(x=>selected.includes(x));let score=Math.round((idealHits.length/g.ideal.length)*80+(supportHits.length/Math.max(1,g.support.length))*20);score=Math.min(100,score);let level=score>=85?'MUITO ALTA':score>=65?'BOA':score>=40?'PARCIAL':'BAIXA';document.querySelector('#alignmentScore').textContent=score+'% • '+level;document.querySelector('#alignmentTitle').textContent='Objetivo: '+g.label;document.querySelector('#alignmentDiagnosis').textContent=score>=85?'A combinação está muito coerente para '+g.why+'.':score>=65?'A combinação tem boa base para '+g.why+', mas ainda pode fechar algumas lacunas.':'O cenário tem iniciativas relevantes, porém ainda não forma um ciclo suficientemente completo para '+g.why+'.';document.querySelector('#alignmentStrength').textContent=idealHits.length?'Você já selecionou pilares centrais: '+idealHits.join(', ')+'.':'O cenário traz capacidades complementares, mas ainda não inclui os pilares centrais deste objetivo.';const missing=g.ideal.filter(x=>!selected.includes(x));document.querySelector('#alignmentGap').textContent=missing.length?'Para fechar melhor o ciclo, faltam: '+missing.join(', ')+'.':'Os pilares essenciais estão contemplados. O próximo desafio é execução, integração e mensuração.';const add=[...missing,...g.support.filter(x=>!selected.includes(x))].slice(0,2);document.querySelector('#alignmentRecommendation').textContent=add.length?'Considere adicionar '+add.join(' + ')+' para aumentar a aderência ao objetivo escolhido.':'Mantenha a combinação e defina indicadores para acompanhar se o resultado esperado está acontecendo.';}
'''
s=s.replace(mark,logic+mark,1)
# call function immediately after selected declaration inside listener
old="const selected=roadmapButtons.filter(b=>b.classList.contains('active')).map(b=>b.dataset.item),out=document.querySelector('.strategyResult');"
new=old+"renderAlignment(selected);"
s=s.replace(old,new,1)
p.write_text(s)
