from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()
css='''
.strategyResult{display:none;margin-top:24px;border-top:1px solid #dfe5ee;padding-top:24px}.strategyResult.show{display:block}.impactGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}.impactCard{background:#f7f8fb;border-radius:16px;padding:15px}.impactHead{display:flex;justify-content:space-between;font-weight:800;font-size:.86rem}.impactBar{height:8px;background:#e2e7ef;border-radius:99px;margin-top:10px;overflow:hidden}.impactFill{height:100%;background:#ffcd19;border-radius:99px;transition:width .45s ease}.strategyReading{background:#071e45;color:#fff;border-radius:20px;padding:22px;margin:18px 0}.strategyReading h3{color:#ffcd19;margin-top:0}.strategyReading p{color:#e9eef7}.strategyFlow{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.strategyFlow span{background:#eef3fa;color:#071e45;padding:9px 12px;border-radius:999px;font-size:.78rem;font-weight:800}.initiativeImpact{margin-top:18px;display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.initiativeImpact article{border:1px solid #dfe5ee;border-radius:16px;padding:16px}.initiativeImpact small{font-weight:800;color:#0d3a74}.initiativeImpact h4{margin:6px 0}.roadmapSteps li{margin-bottom:7px}.simDisclaimer{font-size:.75rem;color:#667085;margin-top:12px}@media(max-width:700px){.impactGrid,.initiativeImpact{grid-template-columns:1fr}}
'''
if '.strategyResult{' not in s:s=s.replace('</style>',css+'\n</style>',1)
new='''<div class="roadmapBox" id="roadmap2027"><div class="sectionHead"><div><div class="kicker">MAX 2027 • SIMULAÇÃO ESTRATÉGICA</div><h2>Onde a Max deve concentrar energia em 2027?</h2></div><p>Monte cenários e veja como cada combinação influencia Cultura, Desenvolvimento, Experiência, Eficiência, Dados e Prevenção.</p></div>
<div class="initiativeGrid">
<button type="button" class="initiative" data-status="ja" data-item="Max em Movimento"><strong>Max em Movimento</strong><span>Programa feminino já existente, integrado às ações de saúde mental e prevenção.</span></button>
<button type="button" class="initiative" data-status="andamento" data-item="NR-1 & Saúde Mental"><strong>NR-1 & Saúde Mental</strong><span>Prevenção, riscos psicossociais, evidências e acompanhamento.</span></button>
<button type="button" class="initiative" data-status="andamento" data-item="GPTW"><strong>GPTW</strong><span>Primeiros passos, diagnóstico, escuta e evolução da cultura.</span></button>
<button type="button" class="initiative active" data-status="2027" data-item="UNIMAX + PDI"><strong>UNIMAX + PDI</strong><span>Trilhas por função, Planta de Desenvolvimento Individual e Chaves Max.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="LNT & T&D"><strong>LNT & T&D</strong><span>Calendário 2027, desenvolvimento e ações por público.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="Onboarding"><strong>Onboarding</strong><span>Experiência estruturada desde a chegada até 90 dias.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="Sólides"><strong>Sólides</strong><span>Perfil comportamental, R&S e apoio à jornada.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="Desempenho"><strong>Avaliação de Desempenho</strong><span>Competências, PDI, OKRs, 360° e evolução.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="People Analytics"><strong>People Analytics</strong><span>Indicadores para decisões de pessoas e liderança.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="Pesquisas"><strong>Pesquisas & Escuta</strong><span>Clima, pulse, experiência e planos de ação.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="Automação"><strong>Automação do RH</strong><span>Fluxos, ponto, solicitações, dados e eficiência.</span></button>
<button type="button" class="initiative" data-status="2027" data-item="MAX PEOPLE"><strong>MAX PEOPLE + Maxiane</strong><span>Portal próprio, IA e experiência digital de RH.</span></button></div>
<button type="button" class="generateRoadmap">Simular minha estratégia →</button>
<div class="strategyResult" aria-live="polite"><h3>Impacto da estratégia</h3><div class="impactGrid" id="impactGrid"></div><div class="strategyReading"><h3 id="strategyTitle"></h3><p id="strategyText"></p><div class="strategyFlow" id="strategyFlow"></div><p id="strategyAttention"></p></div><h3>Como cada prioridade contribui</h3><div class="initiativeImpact" id="initiativeImpact"></div><h3 style="margin-top:26px">Roadmap recomendado</h3><div class="timeline2027"><div class="quarter"><b>Q1 • Fundação</b><ul class="roadmapSteps" id="q1"></ul></div><div class="quarter"><b>Q2 • Construção</b><ul class="roadmapSteps" id="q2"></ul></div><div class="quarter"><b>Q3 • Desenvolvimento</b><ul class="roadmapSteps" id="q3"></ul></div><div class="quarter"><b>Q4 • Evolução</b><ul class="roadmapSteps" id="q4"></ul></div></div><p class="simDisclaimer">Simulação estratégica qualitativa: os índices representam a aderência relativa das iniciativas às dimensões de RH e servem para comparação de cenários, não como indicadores de resultado realizado.</p></div></div>'''
start=s.index('<div class="roadmapBox" id="roadmap2027">')
end=s.index('</div></section>',start)
s=s[:start]+new+s[end:]
old_start=s.index("const roadmapButtons=[...document.querySelectorAll('.initiative')]")
old_end=s.index('\n\n    </script>',old_start)
js=r'''const roadmapButtons=[...document.querySelectorAll('.initiative')];
roadmapButtons.forEach(b=>b.addEventListener('click',()=>b.classList.toggle('active')));
const strategyData={
'Max em Movimento':{w:[18,8,24,2,2,30],goal:'Bem-estar, vínculo e prevenção',result:'Fortalece convivência, movimento, saúde e bem-estar das mulheres da Max.',q:['Manter calendário e adesão','Conectar às ações preventivas','Acompanhar participação','Avaliar aprendizados e continuidade']},
'NR-1 & Saúde Mental':{w:[15,8,16,5,10,40],goal:'Prevenção e gestão de riscos psicossociais',result:'Estrutura prevenção, escuta, evidências e acompanhamento de fatores psicossociais.',q:['Mapear riscos e evidências','Definir plano preventivo','Executar e acompanhar ações','Revisar evidências e plano']},
'GPTW':{w:[35,8,30,3,8,8],goal:'Cultura e experiência',result:'Organiza escuta e plano de evolução da experiência e cultura, sem antecipar resultado de certificação.',q:['Kick-off e diagnóstico','Escuta e plano de ação','Atuar sobre prioridades','Medir evolução da jornada']},
'UNIMAX + PDI':{w:[20,40,18,8,8,2],goal:'Desenvolvimento, retenção e formação interna',result:'Conecta avaliação, PDI e aprendizagem por função em uma jornada contínua de desenvolvimento.',q:['Mapear competências e desenhar PDIs','Publicar Fundação Ser Max e trilhas','Direcionar trilhas pelos gaps','Revisar PDIs e evolução']},
'LNT & T&D':{w:[12,35,15,5,8,8],goal:'Capacitação direcionada',result:'Transforma necessidades de aprendizagem em calendário, públicos e ações de desenvolvimento.',q:['Priorizar necessidades do LNT','Executar calendário por público','Acompanhar adesão e aplicação','Medir efetividade e planejar 2028']},
'Onboarding':{w:[18,18,35,12,5,5],goal:'Experiência e integração',result:'Padroniza a chegada, acelera adaptação e reforça cultura desde o primeiro dia.',q:['Desenhar jornada 0–90 dias','Implantar materiais e rituais','Medir experiência de entrada','Ajustar jornada pelos dados']},
'Sólides':{w:[8,18,10,20,22,3],goal:'Perfil, atração e apoio à gestão',result:'Adiciona perfil comportamental e estrutura de R&S como insumo para decisões de pessoas.',q:['Configurar processos e perfis','Aplicar no R&S e jornadas','Cruzar aprendizados com desenvolvimento','Avaliar uso e aderência']},
'Desempenho':{w:[15,38,15,8,20,3],goal:'Performance e desenvolvimento',result:'Cria ciclo de competências, feedback, PDI e acompanhamento da evolução.',q:['Definir modelo e competências','Rodar primeiro ciclo','Converter gaps em PDI e UNIMAX','Calibrar e medir evolução']},
'People Analytics':{w:[5,8,5,30,45,5],goal:'Decisão orientada por dados',result:'Consolida indicadores para transformar dados de pessoas em decisões de liderança.',q:['Definir KPIs e fontes','Construir painéis prioritários','Criar rotina de análise com gestores','Consolidar tendências e decisões']},
'Pesquisas':{w:[22,8,28,5,28,12],goal:'Escuta e diagnóstico',result:'Transforma percepção dos colaboradores em diagnóstico e planos de ação acompanháveis.',q:['Definir calendário de escuta','Aplicar pesquisas e priorizar temas','Executar planos de ação','Medir evolução das percepções']},
'Automação':{w:[3,3,8,45,25,3],goal:'Eficiência operacional',result:'Reduz tarefas manuais, organiza fluxos e libera capacidade do RH para atuação estratégica.',q:['Mapear gargalos e fluxos','Automatizar rotinas prioritárias','Integrar dados e alertas','Medir ganho operacional']},
'MAX PEOPLE':{w:[8,10,20,38,38,4],goal:'Experiência digital e centralização',result:'Centraliza serviços, dados e IA em uma experiência digital própria de RH.',q:['Priorizar módulos e arquitetura','Implantar fluxos essenciais','Conectar analytics e Maxiane','Consolidar adoção e evolução']}}
const dims=['Cultura','Desenvolvimento','Experiência','Eficiência','Dados','Prevenção'];
document.querySelector('.generateRoadmap')?.addEventListener('click',()=>{const selected=roadmapButtons.filter(b=>b.classList.contains('active')).map(b=>b.dataset.item),out=document.querySelector('.strategyResult');if(!selected.length){out.classList.add('show');document.querySelector('#strategyTitle').textContent='Selecione pelo menos uma prioridade';document.querySelector('#strategyText').textContent='Escolha as iniciativas que deseja comparar para gerar uma leitura estratégica.';return}let scores=[0,0,0,0,0,0];selected.forEach(x=>strategyData[x].w.forEach((v,i)=>scores[i]+=v));const max=Math.max(...scores)||1;scores=scores.map(v=>Math.round(v/max*100));document.querySelector('#impactGrid').innerHTML=dims.map((d,i)=>`<div class="impactCard"><div class="impactHead"><span>${d}</span><span>${scores[i]}%</span></div><div class="impactBar"><div class="impactFill" style="width:${scores[i]}%"></div></div></div>`).join('');const rank=scores.map((v,i)=>[v,i]).sort((a,b)=>b[0]-a[0]);const top=dims[rank[0][1]],second=dims[rank[1][1]],low=dims[rank[rank.length-1][1]];document.querySelector('#strategyTitle').textContent=`Estratégia formada: ${top} + ${second}`;document.querySelector('#strategyText').textContent=`Sua combinação concentra maior impacto em ${top.toLowerCase()} e ${second.toLowerCase()}. As prioridades se complementam para construir uma atuação de RH mais estruturada e conectada.`;document.querySelector('#strategyFlow').innerHTML=({Cultura:['ESCUTAR','ALINHAR','ENGAJAR','EVOLUIR'],Desenvolvimento:['DIAGNOSTICAR','DESENVOLVER','APLICAR','MEDIR'],Experiência:['ACOLHER','ESCUTAR','AGIR','EVOLUIR'],Eficiência:['MAPEAR','AUTOMATIZAR','CENTRALIZAR','GANHAR ESCALA'],Dados:['CENTRALIZAR','MEDIR','ANALISAR','DECIDIR'],Prevenção:['MAPEAR','PREVENIR','ACOMPANHAR','REVISAR']}[top]).map(x=>`<span>${x}</span>`).join('<b>→</b>');document.querySelector('#strategyAttention').innerHTML=`<b>Ponto de atenção:</b> ${low} aparece com menor ênfase neste cenário. Isso não significa uma falha; mostra onde a estratégia escolhida está investindo menos energia.`;document.querySelector('#initiativeImpact').innerHTML=selected.map(x=>`<article><small>IMPACTO ESTRATÉGICO</small><h4>${x}</h4><b>${strategyData[x].goal}</b><p>${strategyData[x].result}</p></article>`).join('');['q1','q2','q3','q4'].forEach((id,i)=>{document.querySelector('#'+id).innerHTML=selected.map(x=>`<li><b>${x}:</b> ${strategyData[x].q[i]}</li>`).join('')});out.classList.add('show');out.scrollIntoView({behavior:'smooth',block:'start'})});'''
s=s[:old_start]+js+s[old_end:]
p.write_text(s)
